version: '3'

services:
  db:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=flyway
      - POSTGRES_DB=flyway
      - POSTGRES_PASSWORD=flyway
    ports:
      - "5432:5432"

  app:
    build: .
    working_dir:  /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/flyway
      - SPRING_DATASOURCE_USERNAME=flyway
      - SPRING_DATASOURCE_PASSWORD=flyway
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - UPLOAD_PATH=/home/media/file
    ports:
      - "8080:8080"