spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flyway
    username: flyway
    password: flyway
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/flyway
    user: flyway
    password: flyway
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
